from app.modules.auth.constants.messages import (
    AUDIT_LOGIN_FAILED,
    AUDIT_LOGIN_SUCCESS,
    AUDIT_REGISTER_FAILED,
    AUDIT_REGISTER_SUCCESS,
    CURRENT_PASSWORD_INCORRECT,
    INVALID_OR_EXPIRED_OTP,
    INVALID_VERIFICATION_TOKEN,
    USER_NOT_FOUND,
)

__all__ = [
    "AUDIT_LOGIN_FAILED",
    "AUDIT_LOGIN_SUCCESS",
    "AUDIT_REGISTER_FAILED",
    "AUDIT_REGISTER_SUCCESS",
    "CURRENT_PASSWORD_INCORRECT",
    "INVALID_OR_EXPIRED_OTP",
    "INVALID_VERIFICATION_TOKEN",
    "USER_NOT_FOUND",
]
