"""create_activity_causes_tables

Revision ID: d26545d64587
Revises: 422efb2a2407
Create Date: 2026-10-10 13:24:57.695256

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26545d64587'
down_revision: Union[str, Sequence[str], None] = '422efb2a2407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causes_name'), 'causes', ['name'], unique=True)
    op.create_index(op.f('ix_causes_slug'), 'causes', ['slug'], unique=True)
    op.create_table('activity_causes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('cause_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'cause_id', name='uq_activity_causes_activity_cause')
    )
    op.create_index(op.f('ix_activity_causes_activity_id'), 'activity_causes', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_causes_cause_id'), 'activity_causes', ['cause_id'], unique=False)
    op.alter_column('activity', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activity', 'capacity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_events_date'), table_name='activity')
    op.drop_index(op.f('ix_events_name'), table_name='activity')
    op.drop_index(op.f('ix_events_owner_id'), table_name='activity')
    op.create_index(op.f('ix_activity_date'), 'activity', ['date'], unique=False)
    op.create_index(op.f('ix_activity_name'), 'activity', ['name'], unique=False)
    op.create_index(op.f('ix_activity_owner_id'), 'activity', ['owner_id'], unique=False)
    op.create_index(op.f('ix_activity_status'), 'activity', ['status'], unique=False)
    op.alter_column('activity_detail', 'created_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activity_detail', 'modified_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activity_detail', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('activity_detail_activity_id_key'), 'activity_detail', type_='unique')
    op.drop_index(op.f('ix_activity_detail_activity_id'), table_name='activity_detail')
    op.create_index(op.f('ix_activity_detail_activity_id'), 'activity_detail', ['activity_id'], unique=True)
    op.drop_constraint(op.f('activity_detail_activity_id_fkey'), 'activity_detail', type_='foreignkey')
    op.create_foreign_key(None, 'activity_detail', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_detail', type_='foreignkey')
    op.create_foreign_key(op.f('activity_detail_activity_id_fkey'), 'activity_detail', 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_activity_detail_activity_id'), table_name='activity_detail')
    op.create_index(op.f('ix_activity_detail_activity_id'), 'activity_detail', ['activity_id'], unique=False)
    op.create_unique_constraint(op.f('activity_detail_activity_id_key'), 'activity_detail', ['activity_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('activity_detail', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_detail', 'modified_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('activity_detail', 'created_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_status'), table_name='activity')
    op.drop_index(op.f('ix_activity_owner_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_index(op.f('ix_activity_date'), table_name='activity')
    op.create_index(op.f('ix_events_owner_id'), 'activity', ['owner_id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'activity', ['name'], unique=False)
    op.create_index(op.f('ix_events_date'), 'activity', ['date'], unique=False)
    op.alter_column('activity', 'capacity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('activity', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_causes_cause_id'), table_name='activity_causes')
    op.drop_index(op.f('ix_activity_causes_activity_id'), table_name='activity_causes')
    op.drop_table('activity_causes')
    op.drop_index(op.f('ix_causes_slug'), table_name='causes')
    op.drop_index(op.f('ix_causes_name'), table_name='causes')
    op.drop_table('causes')
    # ### end Alembic commands ###
